/* Hardware catalogue — Stand Mai 2026.
 * Alle Preise in € (inkl. MwSt. Schätzungen für 2026).
 * Baseline LF=0.6 (Lastfaktor für Stromberechnung).
 */

window.HARDWARE_CATALOGUE = [
  {
    id: 'studio-m5ultra',
    name: 'Mac Studio · M5 Ultra',
    short: 'M5 Ultra Studio',
    category: 'Ultimate Unified Memory',
    vram: 256,
    tflops: 130,
    bandwidth: 1200,
    powerKI: 180,
    powerIdle: 15,
    powerMax: 350,
    price: 9999,
    resaleFactor: 0.75,
    composition: 'Dual-M5-Max Architektur · 256 GB Unified RAM',
    color: '#000000',
    bestFor: 'Modelle >120B Parameter, maximale Context-Windows',
    sources: ['https://o-mega.ai/articles/macbook-m5-pro-and-max-the-ai-professional-s-computer'],
    verified: '2026-05-12',
    notes: ['Das absolute Limit für lautlose Desktop-Inferenz']
  },
  {
    id: 'server-4r9700',
    name: 'Server · EPYC 9135 + 4× R9700',
    short: 'Server 4× R9700',
    category: 'Multi-GPU Cluster',
    vram: 128,
    tflops: 382,
    bandwidth: 2560,
    powerKI: 650,
    powerIdle: 270,
    powerMax: 1450,
    price: 9500,
    resaleFactor: 0.45,
    composition: 'Basis 250 W + 4× GPU (~100 W/Karte Inferenz-Last)',
    color: '#8a7ff5',
    bestFor: 'Multi-GPU Hosting, große Modelle bis 128 GB VRAM',
    sources: [],
    verified: '2026-05-12',
    notes: ['Professionelles Rack-System']
  },
  {
    id: 'ws-2r9700',
    name: 'Workstation · 2× Radeon R9700',
    short: 'WS 2× R9700',
    category: 'Dual-GPU Workstation',
    vram: 64,
    tflops: 191,
    bandwidth: 1280,
    powerKI: 460,
    powerIdle: 160,
    powerMax: 760,
    price: 4600,
    resaleFactor: 0.50,
    composition: 'PC 100 W + 2× GPU (~180 W/Karte)',
    color: '#5fb3d4',
    bestFor: 'Dichte 64-GB-Modelle mit hohem Durchsatz',
    sources: [],
    verified: '2026-05-12',
    notes: []
  },
  {
    id: 'ws-am5-9950x-r9700',
    name: 'Pro-Workstation · Ryzen 9 9950X + Radeon R9700',
    short: 'AM5 Pro-WS',
    category: 'Future-Proof Desktop',
    vram: 32,
    tflops: 96,
    bandwidth: 640,
    powerKI: 420,
    powerIdle: 75,
    powerMax: 850,
    price: 3600,
    resaleFactor: 0.60,
    composition: 'Full Desktop (PCIe 5.0 x16 Anbindung)',
    color: '#f5a623',
    bestFor: 'Maximale Upgradability, Multi-GPU Option, Proxmox-Power',
    sources: ['https://www.phoronix.com/review/amd-radeon-ai-pro-r9700'],
    verified: '2026-05-12',
    notes: ['Bestes Thermal Management', 'Platz für zweite GPU']
  },
  {
    id: 'studio-m5max',
    name: 'Mac Studio · M5 Max',
    short: 'M5 Max Studio',
    category: 'Unified Memory · Apple Silicon',
    vram: 128,
    tflops: 65,
    bandwidth: 600,
    powerKI: 90,
    powerIdle: 10,
    powerMax: 215,
    price: 4600,
    resaleFactor: 0.70,
    composition: 'Stationär · 128 GB Unified RAM',
    color: '#95a5a6',
    bestFor: 'Dauerlast Agenten, große Modelle, bester Werterhalt',
    sources: ['https://o-mega.ai/articles/macbook-m5-pro-and-max-the-ai-professional-s-computer'],
    verified: '2026-05-12',
    notes: ['Kein natives Proxmox möglich']
  },
  {
    id: 'dgx-spark',
    name: 'NVIDIA DGX Spark (Founders Edition)',
    short: 'DGX Spark FE',
    category: 'Unified Memory · CUDA',
    vram: 128,
    tflops: 100,
    bandwidth: 273,
    powerKI: 160,
    powerIdle: 40,
    powerMax: 240,
    price: 4000,
    resaleFactor: 0.50,
    composition: 'GB10 Grace Blackwell Superchip · 20 ARM-Kerne · 6.144 CUDA-Kerne · 4 TB NVMe',
    color: '#7aa2ff',
    bestFor: 'Stabile CUDA-Umgebung, Prototyping, FP4-Inferenz',
    sources: ['https://www.nvidia.com/en-us/products/workstations/dgx-spark/'],
    verified: '2026-06-09',
    notes: ['Founders Edition · 4 TB NVMe', 'Spezialisiert auf FP4 Inferenz']
  },
  {
    id: 'rtx-spark-n1x',
    name: 'NVIDIA RTX Spark Notebook · N1X',
    short: 'RTX Spark N1X',
    category: 'Unified Memory · CUDA Mobile',
    vram: 128,
    tflops: 100,
    bandwidth: 273,
    powerKI: 90,
    powerIdle: 12,
    powerMax: 140,
    price: 2900,
    resaleFactor: 0.55,
    composition: 'GB10 / N1X · 256-bit LPDDR5X · Laptop-Formfaktor (ab 14 mm)',
    color: '#3ec9c9',
    bestFor: 'Mobile CUDA-Inferenz, große Modelle unterwegs',
    sources: ['https://www.nvidia.com/en-us/products/rtx-spark/'],
    verified: '2026-06-09',
    notes: ['Verfügbar ab Herbst 2026', 'Windows · Arm v9 · Blackwell GPU']
  },
  {
    id: 'rtx-spark-n1',
    name: 'NVIDIA RTX Spark Notebook · N1',
    short: 'RTX Spark N1',
    category: 'Unified Memory · CUDA Mobile',
    vram: 64,
    tflops: 60,
    bandwidth: 137,
    powerKI: 70,
    powerIdle: 10,
    powerMax: 110,
    price: 1800,
    resaleFactor: 0.50,
    composition: 'N1 · 128-bit LPDDR5X · reduzierte Kernanzahl',
    color: '#caa0ff',
    bestFor: 'Günstiger mobiler Einstieg, Modelle bis 64 GB',
    sources: ['https://www.nvidia.com/en-us/products/rtx-spark/'],
    verified: '2026-06-09',
    notes: ['Verfügbar ab Herbst 2026', '128-bit Speicher · ~halbe Bandbreite']
  },
  {
    id: 'mbp-m5max',
    name: 'Apple MacBook Pro · M5 Max',
    short: 'M5 Max',
    category: 'Unified Memory · Apple Silicon',
    vram: 128,
    tflops: 70,
    bandwidth: 614,
    powerKI: 55,
    powerIdle: 12,
    powerMax: 90,
    price: 5100,
    resaleFactor: 0.65,
    composition: 'Hocheffizient · Laptop Formfaktor',
    color: '#d4b550',
    bestFor: 'Mobil, niedrigste Stromkosten, hoher Wiederverkauf',
    sources: ['https://o-mega.ai/articles/macbook-m5-pro-and-max-the-ai-professional-s-computer'],
    verified: '2026-05-12',
    notes: []
  },
  {
    id: 'mbp-m5pro-64',
    name: 'Apple MacBook Pro 14" · M5 Pro (64 GB)',
    short: 'M5 Pro 14"',
    category: 'Unified Memory · Apple Silicon',
    vram: 64,
    tflops: 40,
    bandwidth: 300,
    powerKI: 40,
    powerIdle: 8,
    powerMax: 70,
    price: 3200,
    resaleFactor: 0.68,
    composition: '14" · 64 GB Unified RAM · effizienter Laptop',
    color: '#8fa3b8',
    bestFor: 'Sandboxed lokale Agenten, 14B–32B Modelle, bester Wert/macOS',
    sources: ['https://o-mega.ai/articles/macbook-m5-pro-and-max-the-ai-professional-s-computer'],
    verified: '2026-06-09',
    notes: ['Reicht für 32B-Agenten mit großem Context', 'Sehr leise, lange Akkulaufzeit']
  },
  {
    id: 'gmktec-evo-x2',
    name: 'GMKtec EVO-X2 · AI Max+ 395',
    short: 'EVO-X2',
    category: 'Unified Memory · AMD APU',
    vram: 128,
    tflops: 63,
    bandwidth: 256,
    powerKI: 80,
    powerIdle: 20,
    powerMax: 120,
    price: 3000,
    resaleFactor: 0.45,
    composition: 'Strix Halo · 128 GB LPDDR5X-8000',
    color: '#d18158',
    bestFor: 'Günstigster Einstieg in 128 GB Unified Memory',
    sources: [],
    verified: '2026-05-12',
    notes: ['RAM verlötet', 'Shared Memory mit Proxmox']
  },
  {
    id: 'egpu-pro-bundle',
    name: 'Modular Bundle · MS-02 Ultra + Radeon R9700',
    short: 'MS-02 + R9700 (eGPU)',
    category: 'Modular eGPU Setup',
    vram: 32,
    tflops: 96,
    bandwidth: 640,
    powerKI: 380,
    powerIdle: 45,
    powerMax: 460,
    price: 2500,
    resaleFactor: 0.55,
    composition: 'Mini-PC + eGPU via OCuLink',
    color: '#ff7eb6',
    bestFor: 'Flexibilität, Modell-Wechsel, hoher VRAM-Durchsatz',
    sources: ['https://www.phoronix.com/review/amd-radeon-ai-pro-r9700'],
    verified: '2026-05-12',
    notes: ['VRAM dediziert', 'Host-RAM separat bis 128 GB']
  },
  {
    id: 'minis-n5-pro',
    name: 'Minisforum N5 Pro · Ryzen AI 9 HX PRO 370',
    short: 'N5 Pro (NAS/Agent)',
    category: 'Agent Host · OCuLink Ready',
    vram: 96,
    tflops: 25,
    bandwidth: 120,
    powerKI: 45,
    powerIdle: 15,
    powerMax: 65,
    price: 1850,
    resaleFactor: 0.50,
    composition: 'NAS-Basis mit 5 HDD-Slots + 96 GB RAM',
    color: '#a3d158',
    bestFor: '24/7 Proxmox, Agenten-Hosting, Datenstabilität',
    sources: [],
    verified: '2026-05-12',
    notes: ['ECC-Unterstützung', 'OCuLink für spätere eGPU']
  },
  {
    id: 'ws-w7900',
    name: 'Workstation · 1× Radeon W7900',
    short: 'WS W7900',
    category: 'Single-GPU Workstation',
    vram: 48,
    tflops: 61,
    bandwidth: 864,
    powerKI: 220,
    powerIdle: 80,
    powerMax: 420,
    price: 5500,
    resaleFactor: 0.35,
    composition: 'PC 100 W + 1× GPU (~120 W)',
    color: '#4dd081',
    bestFor: 'Dichte Modelle bis 48 GB, hohe Bandbreite/€',
    sources: [],
    verified: '2026-05-12',
    notes: []
  },
  {
    id: 'cluster-3user-r9700',
    name: 'Shared Cluster · 3× Radeon R9700 (x86)',
    short: '3-User Cluster',
    category: 'Multi-GPU Cluster',
    vram: 96,
    tflops: 288,
    bandwidth: 1920,
    powerKI: 580,
    powerIdle: 140,
    powerMax: 950,
    price: 8200,
    resaleFactor: 0.55,
    composition: 'AM5 Basis (9950X) + 3× R9700 (je 32 GB VRAM)',
    color: '#ff4d4d',
    bestFor: '3 Nutzer mit eigenem GPU-Passthrough in Proxmox',
    sources: [],
    verified: '2026-05-12',
    notes: [
      'Jeder Nutzer erhält exklusiv 32 GB VRAM und 640 GB/s Bandbreite',
      'Echte Kapselung via Proxmox Hypervisor möglich',
      'Hoher Kühlungsbedarf (Fractal Meshify 2 XL empfohlen)'
    ]
  }
];